const { GoogleGenAI } = require('@google/genai');

/**
 * Coaches a draft blog post against the SEO guidelines.
 * @param {string} keyword - The search keyword
 * @param {Array<string>} guidelines - Guidelines generated by the Analyzer agent
 * @param {string} draft - The user's draft text
 * @returns {Promise<Object>} JSON containing coaching feedback
 */
async function coachDraft(keyword, guidelines, draft) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
        throw new Error('GEMINI_API_KEY가 설정되지 않았습니다.');
    }

    const ai = new GoogleGenAI({ apiKey });

    const promptText = `당신은 네이버 블로그 전문 코칭 에이전트입니다.
목표 키워드: "${keyword}"
상위 노출을 위한 SEO 가이드라인 (경쟁사 분석 결과):
${guidelines.map((g, i) => `${i + 1}. ${g}`).join('\n')}

사용자의 초안:
"""
${draft}
"""

분석 및 코칭 요청:
1. 가이드라인 준수율 평가: 제공된 가이드라인을 바탕으로 초안의 SEO 최적화 점수를 매겨주세요. (0~100점)
2. 강점 분석 (Strengths): 가이드라인을 잘 반영하여 상위 노출 가능성을 높인 부분 2가지를 칭찬하세요.
3. 구체적 수정 제안 (Critical Improvements): 
   - 단순한 조언을 넘어, "실제 본문 내용을 어떻게 고쳐야 하는지" 비포/애프터 형식으로 구체적인 예시 문장을 제공하세요.
   - 예: "[수정 전] 눈 건강에는 루테인이 중요합니다. -> [수정 후] '눈 영양제 추천' 키워드를 본문 첫 문장에 배치하고, 루테인의 효능을 타 경쟁사처럼 단순 나열하기보다 본인만의 실제 복용 경험과 엮어서 전문성을 높이세요."
4. 제목 최적화 (Title Alchemy): 클릭률(CTR)을 극대화할 수 있는 제목 3가지를 추천하세요. (키워드 전방 배치, 타겟 명시, 신뢰도 강조 등 각각 다른 전략 적용)

응답은 반드시 아래 JSON 형식에 맞게 작성해주세요 (마크다운 제외, 순수 JSON 텍스트만):
{
  "score": 85,
  "praise": ["잘된 점1", "잘된 점2"],
  "improvements": [
    {"issue": "해당 가이드라인 위반 내용", "suggestion": "[수정 전] ... -> [수정 후] ... (구체적인 수정 제안)"},
    {"issue": "문제점2", "suggestion": "[수정 전] ... -> [수정 후] ... (구체적인 수정 제안)"}
  ],
  "suggestedTitles": ["[전략명] 추천제목1", "[전략명] 추천제목2", "[전략명] 추천제목3"]
}`;

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-3.1-flash-lite-preview',
            contents: promptText,
            config: {
                temperature: 0.5,
            }
        });
        
        let responseText = response.text;
        
        if (responseText.startsWith('```json')) {
            responseText = responseText.replace(/```json\n?/, '').replace(/```\n?$/, '').trim();
        } else if (responseText.startsWith('```')) {
            responseText = responseText.replace(/```\n?/, '').replace(/```\n?$/, '').trim();
        }

        return JSON.parse(responseText);
    } catch (error) {
        console.error('LLM Coach Error:', error);
        throw new Error('코칭 API 오류: ' + (error.message || '알 수 없는 오류'));
    }
}

module.exports = {
    coachDraft
};
